main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index
movie:
  method: 'get'
  path: 'movie/{id}'
  controller: App\Controller\MovieController
  action: index
#middlewares:
#  user:
#    register:
#      method: 'get'
#      path: 'user/reg'
#      controller: App\Controller\RegistrationController
#      action: index
#    auth:
#      method: 'get'
#      path: 'user/auth'
#      controller: App\Controller\RegistrationController
#      action: index

