main:
  method: 'GET'
  path: ~
  controller: App\Controller\HomeController
  action: index
movie:
  method: 'GET'
  path: 'movie/{id}'
  controller: App\Controller\MovieController
  action: index
register:
  method: 'GET'
  path: 'user/reg'
  controller: App\Controller\RegistrationController
  action: index
auth:
  method: ['GET', 'POST']
  path: 'user/auth'
  controller: App\Controller\AuthController
  action: index

